version: "3.9"
services:
  node:
    build: ./node
    environment:
      - DB_FILE=/data/kv.db
      - MAX_IN_FLIGHT=8
      - NODE_HOST=node
      - NODE_PORT=5000
      - NODE_ADDR=http://node:5000
      - SEED_NODE=http://node:5000
    volumes:
      - /data
    ports:
      - "5000"  # Expose one node for gossip seed and external access
    deploy:
      mode: replicated
      replicas: 3

  load-balancer:
    build: ./load_balancer
    environment:
      - SEED_NODE=http://node:5000
    ports:
      - "8000:8000"
    depends_on:
      - node

volumes: {}
